
print('NUMBER')
a=29
print(a)
print(a,type(a))
b=2.5
print(b,type(b))
c=3+4j
print(c,type(c))
print()
print('STRING')
d='This coding done by Ravikant Maurya'
print(d)
f='''Ravikant,Abhishek,Akhilesh,Harsh'''
print(f)
print()
print('LIST')
e=[2,3,4,5,10]
print(e,type(e))
print(e[2])
print()
print('TUPLE')
g=(a,b,c,d,e,f)
print(g,type(g))
print()
print('DICTIONARY')
h={'Name':'Ravi','class':'B.Sc.(hons.)Computer Science'}
print(h)
print()
print('SETS')
i={2,4,5,6,7,8,9,0,10,3,7,3,4,5,6,2}
print(i)
print()
print('TYPE CASTING')
print('Catenation')
j=input("Enter the value1:-")
k=input("Enter the value2:-")
print(j+k)
print()
print('int')
l=int(input("Enter the value2:-"))
m=int(input("Enter the value3:-"))
print(m+l)
print()
print('float')
n=float(input("Enter the value1:-"))
o=float(input("Enter the value2:-"))
print(n+o)
print()
print('eval')
p=eval(input("Enter the value1:-"))
q=eval(input("Enter the value2:-"))
print(p+q)
print()
